recaptcha {
    // These keys are generated by the ReCaptcha service
	publicKey = "6LfouroSAAAAACbTdoYOu7OqklMMAnK83nD1vpmX"
	privateKey = "6LfouroSAAAAALOHrpPqe1bDS11NFB42wjU1C0jT"

	// Include the noscript tags in the generated captcha
	includeNoScript = true
}

environments {
  development {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = false

      // Communicate using HTTPS
      useSecureAPI = false
    }
  }
  production {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = true
    }
  }
}